markdown: GFM
title: Translator-Ava Hsieh-Portfolio
description: Showcase Ava Hsieh's English-Chinese translation works

theme: jekyll-theme-cayman

baseurl: "translate/" 

collections:
  Chinese-English:
    output: true
    
  English-Chinese:
    output: true
